name: Mobile Amazon Reviews
maintainers:
- 4f03b89e-f0e0-4391-880c-0be35303ef2f
platforms:
- linux-64
environments:
  default:
  - environment.yaml
commands:
  serve:
    cmd: panel serve Mobile_Amazon_Reviews.ipynb
